name: production build and deploy

on:
  push:
    branches: [main]

jobs:
  build:
    name: Build Project
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Use Node.js 16
        uses: actions/setup-node@v1
        with:
          node-version: 16

      - name: Install
        run: npm install

      - name: Install smartcontroller
        run: npm install smartcontroller@3.2.8

      - name: Build
        run: npm run build

      - name: Upload build folder
        uses: actions/upload-artifact@v2
        with:
          name: build
          path: build/

  deploy:
    name: Deploy Project
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Download build folder
        uses: actions/download-artifact@v2
        with:
          name: build
          path: build/

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4.2.2
        with:
          repository-name: fraser-dempster/fraser-dempster.github.io
          branch: main
          folder: build
          target-folder: l4-project-interactive-game
          clean: true
          token: ${{ secrets.deploy }}

